# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 761, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.connection_layout = QtWidgets.QVBoxLayout()
        self.connection_layout.setObjectName("connection_layout")
        self.connection_status_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.connection_status_label.setObjectName("connection_status_label")
        self.connection_layout.addWidget(self.connection_status_label)
        self.connect_button_layout = QtWidgets.QHBoxLayout()
        self.connect_button_layout.setObjectName("connect_button_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connect_button_layout.addItem(spacerItem)
        self.connect_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.connect_button.setObjectName("connect_button")
        self.connect_button_layout.addWidget(self.connect_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connect_button_layout.addItem(spacerItem1)
        self.connection_layout.addLayout(self.connect_button_layout)
        self.main_layout.addLayout(self.connection_layout)
        self.table_layout = QtWidgets.QHBoxLayout()
        self.table_layout.setObjectName("table_layout")
        self.table_view = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.table_view.setObjectName("table_view")
        self.table_layout.addWidget(self.table_view)
        self.main_layout.addLayout(self.table_layout)
        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_db = QtWidgets.QMenu(self.menu_bar)
        self.menu_db.setObjectName("menu_db")
        MainWindow.setMenuBar(self.menu_bar)
        self.menu_bar.addAction(self.menu_db.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Клиника пластической хирургии \"Билли Джин\""))
        self.connection_status_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Connection status</span></p></body></html>"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.menu_db.setTitle(_translate("MainWindow", "Database"))
