# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SearchDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchDialog(object):
    def setupUi(self, SearchDialog):
        SearchDialog.setObjectName("SearchDialog")
        SearchDialog.resize(290, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchDialog.sizePolicy().hasHeightForWidth())
        SearchDialog.setSizePolicy(sizePolicy)
        SearchDialog.setMinimumSize(QtCore.QSize(290, 100))
        SearchDialog.setMaximumSize(QtCore.QSize(290, 100))
        self.verticalLayoutWidget = QtWidgets.QWidget(SearchDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 274, 84))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.vertical_layout.setObjectName("vertical_layout")
        self.no_results_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.no_results_label.setObjectName("no_results_label")
        self.vertical_layout.addWidget(self.no_results_label)
        self.phone_number_box = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.phone_number_box.setObjectName("phone_number_box")
        self.vertical_layout.addWidget(self.phone_number_box, 0, QtCore.Qt.AlignBottom)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.search_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.search_button.setObjectName("search_button")
        self.buttons_layout.addWidget(self.search_button, 0, QtCore.Qt.AlignTop)
        self.cancel_search_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel_search_button.setObjectName("cancel_search_button")
        self.buttons_layout.addWidget(self.cancel_search_button, 0, QtCore.Qt.AlignTop)
        self.vertical_layout.addLayout(self.buttons_layout)

        self.retranslateUi(SearchDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchDialog)

    def retranslateUi(self, SearchDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchDialog.setWindowTitle(_translate("SearchDialog", "Search by phone"))
        self.no_results_label.setText(_translate("SearchDialog", "<html><head/><body><p align=\"center\">No results.</p></body></html>"))
        self.phone_number_box.setPlaceholderText(_translate("SearchDialog", "Enter patient\'s phone number..."))
        self.search_button.setText(_translate("SearchDialog", "Search"))
        self.cancel_search_button.setText(_translate("SearchDialog", "Cancel"))
