# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SetDateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetDateDialog(object):
    def setupUi(self, SetDateDialog):
        SetDateDialog.setObjectName("SetDateDialog")
        SetDateDialog.resize(220, 100)
        SetDateDialog.setMinimumSize(QtCore.QSize(220, 100))
        SetDateDialog.setMaximumSize(QtCore.QSize(220, 100))
        self.verticalLayoutWidget = QtWidgets.QWidget(SetDateDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 197, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.vertical_layout.setObjectName("vertical_layout")
        self.date_edit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.date_edit.setObjectName("date_edit")
        self.vertical_layout.addWidget(self.date_edit)
        self.horizonta_layout = QtWidgets.QHBoxLayout()
        self.horizonta_layout.setObjectName("horizonta_layout")
        self.set_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.set_button.setObjectName("set_button")
        self.horizonta_layout.addWidget(self.set_button)
        self.cancel_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizonta_layout.addWidget(self.cancel_button)
        self.vertical_layout.addLayout(self.horizonta_layout)

        self.retranslateUi(SetDateDialog)
        QtCore.QMetaObject.connectSlotsByName(SetDateDialog)

    def retranslateUi(self, SetDateDialog):
        _translate = QtCore.QCoreApplication.translate
        SetDateDialog.setWindowTitle(_translate("SetDateDialog", "Edit date"))
        self.date_edit.setDisplayFormat(_translate("SetDateDialog", "MM.dd.yyyy"))
        self.set_button.setText(_translate("SetDateDialog", "Set new date"))
        self.cancel_button.setText(_translate("SetDateDialog", "Cancel"))
